# Generated by Django 2.2.7 on 2020-03-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_topic_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='哈哈')),
            ],
        ),
    ]
