# Generated by Django 2.2.7 on 2020-03-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
