# Generated by Django 2.2.7 on 2020-03-18 08:57

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=mdeditor.fields.MDTextField(max_length=4000),
        ),
    ]
