# Generated by Django 2.2.7 on 2020-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_auto_20200318_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=4000),
        ),
    ]
